version: "3.9"
services:
  # inference:
  #   build:
  #     context: ./services/inference
  #   ports:
  #     - "3003:3003" # here modified from 5000
  #   environment:
  #     - ENV=development # production
  #   depends_on:
  #     - database

  database:
    build:
      context: ./services/database
    ports:
      - "3002:3002"  # Cassandra's default port 9042
    volumes:
      - cassandra-data:/var/lib/cassandra
  
  # stats:
  #   build:
  #     context: ./services/stats
  #   ports:
  #     - "3002:3002"
  #   depends_on:
  #     - database

volumes:
  cassandra-data: